apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.1
        env:
        - name: discovery.type
          value: single-node
        - name: plugins.security.disabled
          value: "true"
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: logging
spec:
  selector:
    app: opensearch
  ports:
  - port: 9200
    targetPort: 9200
  type: ClusterIP
